### ISSUE TITLE
Check that generated ABI matches `RenPool`

### ISSUE THREAD

**Issue by acuarica** [renpool/renpool-contracts#27]
Add a new job to CI that checks whether the generated artifact ABI matches `RenPool`.

Use the following job:

```yaml
  check-abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: git --no-pager diff --exit-code artifacts/contracts/RenPool.sol/RenPool.json
```
